-- MySQL Script generated by MySQL Workbench
-- Fri Oct 25 14:23:59 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projetoredes
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `projetoredes` ;

-- -----------------------------------------------------
-- Schema projetoredes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetoredes` DEFAULT CHARACTER SET utf8 ;
USE `projetoredes` ;

-- -----------------------------------------------------
-- Table `projetoredes`.`artistas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetoredes`.`artistas` ;

CREATE TABLE IF NOT EXISTS `projetoredes`.`artistas` (
  `id_artistas` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `popularidade` INT NOT NULL,
  PRIMARY KEY (`id_artistas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoredes`.`musicas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetoredes`.`musicas` ;

CREATE TABLE IF NOT EXISTS `projetoredes`.`musicas` (
  `id_musicas` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `popularidade` INT NOT NULL,
  `duracao` INT NOT NULL,
  `energia` INT NOT NULL,
  `dancabilidade` INT NOT NULL,
  `id_artistas` INT NOT NULL,
  PRIMARY KEY (`id_musicas`),
  INDEX `artistas_id_idx` (`id_artistas` ASC) VISIBLE,
  CONSTRAINT `artistas_id`
    FOREIGN KEY (`id_artistas`)
    REFERENCES `projetoredes`.`artistas` (`id_artistas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoredes`.`playlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetoredes`.`playlist` ;

CREATE TABLE IF NOT EXISTS `projetoredes`.`playlist` (
  `id_playlist` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `genero` VARCHAR(45) NULL,
  PRIMARY KEY (`id_playlist`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoredes`.`playlist_musicas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetoredes`.`playlist_musicas` ;

CREATE TABLE IF NOT EXISTS `projetoredes`.`playlist_musicas` (
  `id_musicas` INT NOT NULL,
  `id_playlist` INT NOT NULL,
  PRIMARY KEY (`id_musicas`, `id_playlist`),
  INDEX `fk_musicas_has_playlist_playlist1_idx` (`id_playlist` ASC) VISIBLE,
  INDEX `fk_musicas_has_playlist_musicas1_idx` (`id_musicas` ASC) VISIBLE,
  CONSTRAINT `fk_musicas_has_playlist_musicas1`
    FOREIGN KEY (`id_musicas`)
    REFERENCES `projetoredes`.`musicas` (`id_musicas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_musicas_has_playlist_playlist1`
    FOREIGN KEY (`id_playlist`)
    REFERENCES `projetoredes`.`playlist` (`id_playlist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
