-- MySQL Script generated by MySQL Workbench
-- seg 30 set 2019 14:56:14 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetoredes` DEFAULT CHARACTER SET utf8 ;
USE `projetoredes` ;

-- -----------------------------------------------------
-- Table `mydb`.`artistas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetoredes`.`artistas` ;

CREATE TABLE IF NOT EXISTS `projetoredes`.`artistas` (
  `id_artistas` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL UNIQUE,
  `popularidade` INT NOT NULL,
  PRIMARY KEY (`id_artistas`)
  )
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `projetoredes`.`edges` (
  `origem` VARCHAR(100) NOT NULL,
  `destino` VARCHAR(100) NOT NULL
  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`musicas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetoredes`.`musicas` ;

CREATE TABLE IF NOT EXISTS `projetoredes`.`musicas` (
  `id_musicas` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NULL,
  `popularidade` INT NOT NULL,
  `duracao` INT NOT NULL,
  `energia` INT NOT NULL,
  `dancabilidade` INT NOT NULL,
  `id_artistas` INT NOT NULL,
  PRIMARY KEY (`id_musicas`),
  INDEX `artistas_id_idx` (`id_artistas` ASC) VISIBLE,
  CONSTRAINT `artistas_id`
    FOREIGN KEY (`id_artistas`)
    REFERENCES `mydb`.`artistas` (`id_artistas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
